export const ADD_FILTERS = "ADD_FILTERS";
export const GET_RESULTS = "GET_RESULTS";
export const SEARCH_REQUEST_STARTED = "SEARCH_REQUEST_STARTED";
export const SEARCH_REQUEST_FAILED = "SEARCH_REQUEST_FAILED";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
